import type { Metadata } from "next";
import "../styles/globals.css";
import "leaflet/dist/leaflet.css";
import Header from "@/components/site-header";

export const metadata: Metadata = {
	title: "QuakeAlert - Real-time Earthquake Alerts and Information",
	description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
      
        <main className="flex-1">
          <Header/>
          {children}
        </main>
      </body>
    </html>
    
  )
}